module SkelGrammar where

-- Haskell module generated by the BNF converter

import AbsGrammar
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Program stmts -> failure x
transTopDef :: TopDef -> Result
transTopDef x = case x of
  FnDecl type_ ident args block -> failure x
  VarDecl type_ items -> failure x
  ConstDecl type_ items -> failure x
transItem :: Item -> Result
transItem x = case x of
  NoInit ident -> failure x
  Init ident expr -> failure x
transArg :: Arg -> Result
transArg x = case x of
  Arg type_ ident -> failure x
transBlock :: Block -> Result
transBlock x = case x of
  Block stmts -> failure x
transStmt :: Stmt -> Result
transStmt x = case x of
  Empty -> failure x
  BStmt block -> failure x
  Ass ident expr -> failure x
  Incr ident -> failure x
  Decr ident -> failure x
  Ret expr -> failure x
  VRet -> failure x
  Cond expr stmt -> failure x
  ElseCond expr stmt1 stmt2 -> failure x
  While expr stmt -> failure x
  For ident expr1 expr2 stmt -> failure x
  Break -> failure x
  Continue -> failure x
  StmtExp expr -> failure x
  StmtDecl topdef -> failure x
transType :: Type -> Result
transType x = case x of
  Int -> failure x
  Str -> failure x
  Bool -> failure x
  Void -> failure x
transExpr :: Expr -> Result
transExpr x = case x of
  EVar ident -> failure x
  EInt integer -> failure x
  ETrue -> failure x
  EFalse -> failure x
  EApp ident exprs -> failure x
  EString string -> failure x
  Neg expr -> failure x
  Not expr -> failure x
  EMul expr1 mulop expr2 -> failure x
  EAdd expr1 addop expr2 -> failure x
  ERel expr1 relop expr2 -> failure x
  EAnd expr1 expr2 -> failure x
  EOr expr1 expr2 -> failure x
transAddOp :: AddOp -> Result
transAddOp x = case x of
  Plus -> failure x
  Minus -> failure x
transMulOp :: MulOp -> Result
transMulOp x = case x of
  Mul -> failure x
  Div -> failure x
  Mod -> failure x
transRelOp :: RelOp -> Result
transRelOp x = case x of
  Lth -> failure x
  Le -> failure x
  Gth -> failure x
  Ge -> failure x
  Eq -> failure x
  Ne -> failure x

